# BioMuse Task Configuration
# Configuration for benchmarking LLMs using Zotero metadata

# Model configurations
models:
  gpt4:
    name: "gpt-4o"
    temperature: 0.2
    max_tokens: 256
    provider: "openai"
  
  claude:
    name: "claude-3-5-sonnet-20241022"
    temperature: 0.2
    max_tokens: 256
    provider: "anthropic"
  
  llama2:
    name: "llama-2-13b"
    temperature: 0.0
    max_tokens: 256
    provider: "local"
    quantization: "4bit"
  
  biomuse_rag:
    name: "biomuse-rag"
    temperature: 0.2
    max_tokens: 256
    provider: "custom"
    retrieval_top_k: 5

# Task generation parameters
tasks:
  retrieval:
    num_tasks: 50
    top_k: 3
    query_types: ["tag_based", "abstract_paraphrase", "cluster_centroid"]
    include_context: true
  
  tag_prediction:
    num_tasks: 50
    max_tags: 5
    include_abstract: true
    include_notes: false
  
  summarization:
    num_tasks: 50
    max_length: 200
    include_notes: true
    hallucination_detection: true
  
  classification:
    num_tasks: 50
    domains: ["cancer_evolution", "protein_structure", "gene_regulation"]

# Evaluation metrics
evaluation:
  retrieval_metrics: ["precision", "recall", "f1", "ndcg"]
  tag_metrics: ["macro_f1", "micro_f1", "jaccard_similarity"]
  summarization_metrics: ["rouge_l", "bertscore", "hallucination_rate"]
  classification_metrics: ["accuracy", "adjusted_rand_index"]

# Graph construction parameters
graph:
  edge_types: ["shared_tag", "collection", "related_item", "abstract_similarity"]
  similarity_threshold: 0.7
  max_edges_per_node: 10

# Data processing
data:
  zotero_export_format: "rdf"
  min_abstract_length: 50
  required_fields: ["title", "abstract"]
  collection_mapping:
    cancer_evolution: ["cancer", "evolution", "genomics"]
    protein_structure: ["protein", "structure", "prediction"]
    gene_regulation: ["gene", "regulation", "transcription"]

# Logging and output
output:
  results_dir: "results"
  cache_dir: "cache"
  log_level: "INFO"
  save_intermediate: true
